name: local
description: "Local package for Pokemon DB"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  dartz: ^0.10.1
  sqflite: ^2.4.1
  path: ^1.9.0

  repository:
    path: ../repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  sqflite_common_ffi: ^2.3.4

flutter:
