arb-dir: lib/src/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/src/l10n/gen
output-class: AppLocalizations
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false