name: pokemon_db
description: "A Pokemon Database written in Flutter using https://pokeapi.co/"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.2

  domain:
    path: domain
  repository:
    path: repository
  data:
    path: data
  local:
    path: local
  presentation:
    path: presentation

dependency_overrides:
  flutter_lints: ^5.0.0
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  get_it: ^8.0.2
  collection: ^1.19.1
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  json_serializable: ^6.9.0
  sqflite: ^2.4.1
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.4+3
  dio: ^5.7.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PokemonBW
      fonts:
        - asset: fonts/pokemon-bw.ttf

  assets:
    - assets/