// Mocks generated by Mockito 5.4.4 from annotations
// in presentation/test/pokedex/converters/pokedex_presentation_converter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:domain/domain.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:presentation/src/l10n/gen/presentation_localizations.dart'
    as _i5;
import 'package:presentation/src/pokedex/converters/pokedex_pokemon_presentation_converter.dart'
    as _i3;
import 'package:presentation/src/pokedex/models/pokedex_pokemon_presentation_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokedexPokemonPresentationModel_0 extends _i1.SmartFake
    implements _i2.PokedexPokemonPresentationModel {
  _FakePokedexPokemonPresentationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokedexPokemonPresentationConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexPokemonPresentationConverter extends _i1.Mock
    implements _i3.PokedexPokemonPresentationConverter {
  MockPokedexPokemonPresentationConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.PokedexPokemonPresentationModel> convertList(
    List<_i4.PokemonModel>? pokemonList,
    int? pokedexId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertList,
          [
            pokemonList,
            pokedexId,
          ],
        ),
        returnValue: <_i2.PokedexPokemonPresentationModel>[],
      ) as List<_i2.PokedexPokemonPresentationModel>);

  @override
  _i2.PokedexPokemonPresentationModel convertPokedexPokemon(
    _i4.PokemonModel? pokemon,
    int? pokedexId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertPokedexPokemon,
          [
            pokemon,
            pokedexId,
          ],
        ),
        returnValue: _FakePokedexPokemonPresentationModel_0(
          this,
          Invocation.method(
            #convertPokedexPokemon,
            [
              pokemon,
              pokedexId,
            ],
          ),
        ),
      ) as _i2.PokedexPokemonPresentationModel);
}

/// A class which mocks [PresentationLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresentationLocalizations extends _i1.Mock
    implements _i5.PresentationLocalizations {
  MockPresentationLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName => (super.noSuchMethod(
        Invocation.getter(#localeName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#localeName),
        ),
      ) as String);

  @override
  String get somethingWentWrong => (super.noSuchMethod(
        Invocation.getter(#somethingWentWrong),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#somethingWentWrong),
        ),
      ) as String);

  @override
  String get emptyError => (super.noSuchMethod(
        Invocation.getter(#emptyError),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#emptyError),
        ),
      ) as String);

  @override
  String get backButton => (super.noSuchMethod(
        Invocation.getter(#backButton),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#backButton),
        ),
      ) as String);

  @override
  String get openNavigationMenu => (super.noSuchMethod(
        Invocation.getter(#openNavigationMenu),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#openNavigationMenu),
        ),
      ) as String);

  @override
  String get image => (super.noSuchMethod(
        Invocation.getter(#image),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
      ) as String);

  @override
  String get pokemonTypes => (super.noSuchMethod(
        Invocation.getter(#pokemonTypes),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pokemonTypes),
        ),
      ) as String);

  @override
  String get national => (super.noSuchMethod(
        Invocation.getter(#national),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#national),
        ),
      ) as String);

  @override
  String get kanto => (super.noSuchMethod(
        Invocation.getter(#kanto),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#kanto),
        ),
      ) as String);

  @override
  String get johto => (super.noSuchMethod(
        Invocation.getter(#johto),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#johto),
        ),
      ) as String);

  @override
  String get hoenn => (super.noSuchMethod(
        Invocation.getter(#hoenn),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hoenn),
        ),
      ) as String);

  @override
  String get sinnoh => (super.noSuchMethod(
        Invocation.getter(#sinnoh),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#sinnoh),
        ),
      ) as String);

  @override
  String get unova => (super.noSuchMethod(
        Invocation.getter(#unova),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#unova),
        ),
      ) as String);

  @override
  String get ransei => (super.noSuchMethod(
        Invocation.getter(#ransei),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ransei),
        ),
      ) as String);

  @override
  String get kalos => (super.noSuchMethod(
        Invocation.getter(#kalos),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#kalos),
        ),
      ) as String);

  @override
  String get alola => (super.noSuchMethod(
        Invocation.getter(#alola),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#alola),
        ),
      ) as String);

  @override
  String get melemele => (super.noSuchMethod(
        Invocation.getter(#melemele),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#melemele),
        ),
      ) as String);

  @override
  String get akala => (super.noSuchMethod(
        Invocation.getter(#akala),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#akala),
        ),
      ) as String);

  @override
  String get ulaula => (super.noSuchMethod(
        Invocation.getter(#ulaula),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ulaula),
        ),
      ) as String);

  @override
  String get poni => (super.noSuchMethod(
        Invocation.getter(#poni),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#poni),
        ),
      ) as String);

  @override
  String get galar => (super.noSuchMethod(
        Invocation.getter(#galar),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#galar),
        ),
      ) as String);

  @override
  String get hisui => (super.noSuchMethod(
        Invocation.getter(#hisui),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hisui),
        ),
      ) as String);

  @override
  String get paldea => (super.noSuchMethod(
        Invocation.getter(#paldea),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#paldea),
        ),
      ) as String);

  @override
  String get rby => (super.noSuchMethod(
        Invocation.getter(#rby),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#rby),
        ),
      ) as String);

  @override
  String get gsc => (super.noSuchMethod(
        Invocation.getter(#gsc),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#gsc),
        ),
      ) as String);

  @override
  String get rse => (super.noSuchMethod(
        Invocation.getter(#rse),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#rse),
        ),
      ) as String);

  @override
  String get frlg => (super.noSuchMethod(
        Invocation.getter(#frlg),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#frlg),
        ),
      ) as String);

  @override
  String get dp => (super.noSuchMethod(
        Invocation.getter(#dp),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#dp),
        ),
      ) as String);

  @override
  String get pt => (super.noSuchMethod(
        Invocation.getter(#pt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pt),
        ),
      ) as String);

  @override
  String get hgss => (super.noSuchMethod(
        Invocation.getter(#hgss),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hgss),
        ),
      ) as String);

  @override
  String get bw => (super.noSuchMethod(
        Invocation.getter(#bw),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#bw),
        ),
      ) as String);

  @override
  String get b2w2 => (super.noSuchMethod(
        Invocation.getter(#b2w2),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#b2w2),
        ),
      ) as String);

  @override
  String get xy => (super.noSuchMethod(
        Invocation.getter(#xy),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#xy),
        ),
      ) as String);

  @override
  String get oras => (super.noSuchMethod(
        Invocation.getter(#oras),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#oras),
        ),
      ) as String);

  @override
  String get sm => (super.noSuchMethod(
        Invocation.getter(#sm),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#sm),
        ),
      ) as String);

  @override
  String get usum => (super.noSuchMethod(
        Invocation.getter(#usum),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#usum),
        ),
      ) as String);

  @override
  String get lgo => (super.noSuchMethod(
        Invocation.getter(#lgo),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#lgo),
        ),
      ) as String);

  @override
  String get swsh => (super.noSuchMethod(
        Invocation.getter(#swsh),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#swsh),
        ),
      ) as String);

  @override
  String get bdsp => (super.noSuchMethod(
        Invocation.getter(#bdsp),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#bdsp),
        ),
      ) as String);

  @override
  String get pla => (super.noSuchMethod(
        Invocation.getter(#pla),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pla),
        ),
      ) as String);

  @override
  String get sv => (super.noSuchMethod(
        Invocation.getter(#sv),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#sv),
        ),
      ) as String);

  @override
  String get lza => (super.noSuchMethod(
        Invocation.getter(#lza),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#lza),
        ),
      ) as String);

  @override
  String get conq => (super.noSuchMethod(
        Invocation.getter(#conq),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#conq),
        ),
      ) as String);

  @override
  String get sunMoon => (super.noSuchMethod(
        Invocation.getter(#sunMoon),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#sunMoon),
        ),
      ) as String);

  @override
  String get ultraSunUltraMoon => (super.noSuchMethod(
        Invocation.getter(#ultraSunUltraMoon),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ultraSunUltraMoon),
        ),
      ) as String);

  @override
  String get redBlueYellow => (super.noSuchMethod(
        Invocation.getter(#redBlueYellow),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#redBlueYellow),
        ),
      ) as String);

  @override
  String get fireRedLeafGreen => (super.noSuchMethod(
        Invocation.getter(#fireRedLeafGreen),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fireRedLeafGreen),
        ),
      ) as String);

  @override
  String get letsGoPikachuEevee => (super.noSuchMethod(
        Invocation.getter(#letsGoPikachuEevee),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#letsGoPikachuEevee),
        ),
      ) as String);

  @override
  String get goldSilverCrystal => (super.noSuchMethod(
        Invocation.getter(#goldSilverCrystal),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#goldSilverCrystal),
        ),
      ) as String);

  @override
  String get rubySapphireEmerald => (super.noSuchMethod(
        Invocation.getter(#rubySapphireEmerald),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#rubySapphireEmerald),
        ),
      ) as String);

  @override
  String get diamondPearl => (super.noSuchMethod(
        Invocation.getter(#diamondPearl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#diamondPearl),
        ),
      ) as String);

  @override
  String get brilliantDiamondShiningPearl => (super.noSuchMethod(
        Invocation.getter(#brilliantDiamondShiningPearl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#brilliantDiamondShiningPearl),
        ),
      ) as String);

  @override
  String get platinum => (super.noSuchMethod(
        Invocation.getter(#platinum),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#platinum),
        ),
      ) as String);

  @override
  String get heartGoldSoulSilver => (super.noSuchMethod(
        Invocation.getter(#heartGoldSoulSilver),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#heartGoldSoulSilver),
        ),
      ) as String);

  @override
  String get blackWhite => (super.noSuchMethod(
        Invocation.getter(#blackWhite),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#blackWhite),
        ),
      ) as String);

  @override
  String get black2White2 => (super.noSuchMethod(
        Invocation.getter(#black2White2),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#black2White2),
        ),
      ) as String);

  @override
  String get conquest => (super.noSuchMethod(
        Invocation.getter(#conquest),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#conquest),
        ),
      ) as String);

  @override
  String get central => (super.noSuchMethod(
        Invocation.getter(#central),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#central),
        ),
      ) as String);

  @override
  String get coastal => (super.noSuchMethod(
        Invocation.getter(#coastal),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#coastal),
        ),
      ) as String);

  @override
  String get mountain => (super.noSuchMethod(
        Invocation.getter(#mountain),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#mountain),
        ),
      ) as String);

  @override
  String get omegaRubyAlphaSapphire => (super.noSuchMethod(
        Invocation.getter(#omegaRubyAlphaSapphire),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#omegaRubyAlphaSapphire),
        ),
      ) as String);

  @override
  String get swordShield => (super.noSuchMethod(
        Invocation.getter(#swordShield),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#swordShield),
        ),
      ) as String);

  @override
  String get isleOfArmor => (super.noSuchMethod(
        Invocation.getter(#isleOfArmor),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#isleOfArmor),
        ),
      ) as String);

  @override
  String get crownTundra => (super.noSuchMethod(
        Invocation.getter(#crownTundra),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#crownTundra),
        ),
      ) as String);

  @override
  String get legendsArceus => (super.noSuchMethod(
        Invocation.getter(#legendsArceus),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#legendsArceus),
        ),
      ) as String);

  @override
  String get scarlettViolet => (super.noSuchMethod(
        Invocation.getter(#scarlettViolet),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#scarlettViolet),
        ),
      ) as String);

  @override
  String get theTealMask => (super.noSuchMethod(
        Invocation.getter(#theTealMask),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#theTealMask),
        ),
      ) as String);

  @override
  String get theIndigoDisk => (super.noSuchMethod(
        Invocation.getter(#theIndigoDisk),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#theIndigoDisk),
        ),
      ) as String);

  @override
  String get normal => (super.noSuchMethod(
        Invocation.getter(#normal),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#normal),
        ),
      ) as String);

  @override
  String get fire => (super.noSuchMethod(
        Invocation.getter(#fire),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fire),
        ),
      ) as String);

  @override
  String get water => (super.noSuchMethod(
        Invocation.getter(#water),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#water),
        ),
      ) as String);

  @override
  String get electric => (super.noSuchMethod(
        Invocation.getter(#electric),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#electric),
        ),
      ) as String);

  @override
  String get grass => (super.noSuchMethod(
        Invocation.getter(#grass),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#grass),
        ),
      ) as String);

  @override
  String get ice => (super.noSuchMethod(
        Invocation.getter(#ice),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ice),
        ),
      ) as String);

  @override
  String get fighting => (super.noSuchMethod(
        Invocation.getter(#fighting),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fighting),
        ),
      ) as String);

  @override
  String get poison => (super.noSuchMethod(
        Invocation.getter(#poison),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#poison),
        ),
      ) as String);

  @override
  String get ground => (super.noSuchMethod(
        Invocation.getter(#ground),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ground),
        ),
      ) as String);

  @override
  String get flying => (super.noSuchMethod(
        Invocation.getter(#flying),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#flying),
        ),
      ) as String);

  @override
  String get psychic => (super.noSuchMethod(
        Invocation.getter(#psychic),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#psychic),
        ),
      ) as String);

  @override
  String get bug => (super.noSuchMethod(
        Invocation.getter(#bug),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#bug),
        ),
      ) as String);

  @override
  String get rock => (super.noSuchMethod(
        Invocation.getter(#rock),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#rock),
        ),
      ) as String);

  @override
  String get ghost => (super.noSuchMethod(
        Invocation.getter(#ghost),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ghost),
        ),
      ) as String);

  @override
  String get dragon => (super.noSuchMethod(
        Invocation.getter(#dragon),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#dragon),
        ),
      ) as String);

  @override
  String get dark => (super.noSuchMethod(
        Invocation.getter(#dark),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#dark),
        ),
      ) as String);

  @override
  String get steel => (super.noSuchMethod(
        Invocation.getter(#steel),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#steel),
        ),
      ) as String);

  @override
  String get fairy => (super.noSuchMethod(
        Invocation.getter(#fairy),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#fairy),
        ),
      ) as String);

  @override
  String get baseStats => (super.noSuchMethod(
        Invocation.getter(#baseStats),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseStats),
        ),
      ) as String);

  @override
  String get evYield => (super.noSuchMethod(
        Invocation.getter(#evYield),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#evYield),
        ),
      ) as String);

  @override
  String get hp => (super.noSuchMethod(
        Invocation.getter(#hp),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hp),
        ),
      ) as String);

  @override
  String get attack => (super.noSuchMethod(
        Invocation.getter(#attack),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#attack),
        ),
      ) as String);

  @override
  String get attackShort => (super.noSuchMethod(
        Invocation.getter(#attackShort),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#attackShort),
        ),
      ) as String);

  @override
  String get defense => (super.noSuchMethod(
        Invocation.getter(#defense),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#defense),
        ),
      ) as String);

  @override
  String get defenseShort => (super.noSuchMethod(
        Invocation.getter(#defenseShort),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#defenseShort),
        ),
      ) as String);

  @override
  String get specialAttack => (super.noSuchMethod(
        Invocation.getter(#specialAttack),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialAttack),
        ),
      ) as String);

  @override
  String get specialAttackShort => (super.noSuchMethod(
        Invocation.getter(#specialAttackShort),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialAttackShort),
        ),
      ) as String);

  @override
  String get specialAttackTwoLine => (super.noSuchMethod(
        Invocation.getter(#specialAttackTwoLine),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialAttackTwoLine),
        ),
      ) as String);

  @override
  String get specialDefense => (super.noSuchMethod(
        Invocation.getter(#specialDefense),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialDefense),
        ),
      ) as String);

  @override
  String get specialDefenseShort => (super.noSuchMethod(
        Invocation.getter(#specialDefenseShort),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialDefenseShort),
        ),
      ) as String);

  @override
  String get specialDefenseTwoLine => (super.noSuchMethod(
        Invocation.getter(#specialDefenseTwoLine),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#specialDefenseTwoLine),
        ),
      ) as String);

  @override
  String get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#speed),
        ),
      ) as String);

  @override
  String get speedShort => (super.noSuchMethod(
        Invocation.getter(#speedShort),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#speedShort),
        ),
      ) as String);

  @override
  String get zero => (super.noSuchMethod(
        Invocation.getter(#zero),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#zero),
        ),
      ) as String);

  @override
  String get pokedex => (super.noSuchMethod(
        Invocation.getter(#pokedex),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pokedex),
        ),
      ) as String);

  @override
  String get pokedexEntryNumber => (super.noSuchMethod(
        Invocation.getter(#pokedexEntryNumber),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pokedexEntryNumber),
        ),
      ) as String);

  @override
  String get pokemonName => (super.noSuchMethod(
        Invocation.getter(#pokemonName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#pokemonName),
        ),
      ) as String);
}
