// Mocks generated by Mockito 5.4.4 from annotations
// in presentation/test/pokedex/converters/pokedex_presentation_converter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:domain/models/pokemon_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:presentation/pokedex/converters/pokedex_pokemon_presentation_converter.dart'
    as _i3;
import 'package:presentation/pokedex/models/pokedex_pokemon_presentation_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokedexPokemonPresentationModel_0 extends _i1.SmartFake
    implements _i2.PokedexPokemonPresentationModel {
  _FakePokedexPokemonPresentationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokedexPokemonPresentationConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexPokemonPresentationConverter extends _i1.Mock
    implements _i3.PokedexPokemonPresentationConverter {
  MockPokedexPokemonPresentationConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.PokedexPokemonPresentationModel> convertList(
    List<_i4.PokemonModel>? pokemonList,
    int? pokedexId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertList,
          [
            pokemonList,
            pokedexId,
          ],
        ),
        returnValue: <_i2.PokedexPokemonPresentationModel>[],
      ) as List<_i2.PokedexPokemonPresentationModel>);

  @override
  _i2.PokedexPokemonPresentationModel convertPokedexPokemon(
    _i4.PokemonModel? pokemon,
    int? pokedexId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertPokedexPokemon,
          [
            pokemon,
            pokedexId,
          ],
        ),
        returnValue: _FakePokedexPokemonPresentationModel_0(
          this,
          Invocation.method(
            #convertPokedexPokemon,
            [
              pokemon,
              pokedexId,
            ],
          ),
        ),
      ) as _i2.PokedexPokemonPresentationModel);
}
