name: presentation
description: "Presentation package for Pokemon DB"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  equatable: ^2.0.5
  collection: ^1.18.0
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  dartz: ^0.10.1
  cached_network_image: ^3.4.1

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true