// Mocks generated by Mockito 5.4.4 from annotations
// in local/test/pokedex/pokedex_local_should.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:local/converters/pokedex_local_converter.dart' as _i3;
import 'package:local/converters/pokemon_local_converter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:repository/src/models/local/pokedex_local_model.dart' as _i4;
import 'package:repository/src/models/local/pokemon_local_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonLocalModel_0 extends _i1.SmartFake
    implements _i2.PokemonLocalModel {
  _FakePokemonLocalModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokedexLocalConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexLocalConverter extends _i1.Mock
    implements _i3.PokedexLocalConverter {
  MockPokedexLocalConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> convert(_i4.PokedexLocalModel? pokedex) =>
      (super.noSuchMethod(
        Invocation.method(
          #convert,
          [pokedex],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [PokemonLocalConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonLocalConverter extends _i1.Mock
    implements _i5.PokemonLocalConverter {
  MockPokemonLocalConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> convertToDatabase(_i2.PokemonLocalModel? pokemon) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertToDatabase,
          [pokemon],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.PokemonLocalModel convertFromDatabase(
    Map<String, Object?>? pokemon,
    Map<int, int>? entryNumbers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertFromDatabase,
          [
            pokemon,
            entryNumbers,
          ],
        ),
        returnValue: _FakePokemonLocalModel_0(
          this,
          Invocation.method(
            #convertFromDatabase,
            [
              pokemon,
              entryNumbers,
            ],
          ),
        ),
      ) as _i2.PokemonLocalModel);
}
